### ISSUE TITLE
Enhance Configuration System for Flexible Provider Settings

### ISSUE THREAD

**Issue by turisanapo** [heboai/hebo-evals#38]
## Description
Update the Hebo Evals configuration system to support more flexible provider settings, including custom URLs and API keys. This change will make the system more adaptable to different deployment scenarios and provider configurations.

## Current Limitations
- Limited provider configuration options
- Hard-coded base URLs in `provider-config.ts`
- No support for custom API endpoints
- Limited flexibility in authentication configuration

### 1. Configuration Schema
```typescript
interface ProviderConfig {
  provider: supported providers enum;
  baseUrl?: string;  // Optional custom URL
  apiKey?: string;   // Optional API key
  authHeader?: {     // Optional custom auth header configuration
    name: string;
    format: string;
  };
}

interface HeboEvalsConfig {
  providers: {
    [key: string]: ProviderConfig;
  };
  defaultProvider?: string;
  // ... other existing config options
}
```

### 2. Configuration File Format
```yaml
# hebo-evals.config.yaml
providers:
  openai:
    provider: openai
    baseUrl: https://api.openai.com/v1
    apiKey: ${OPENAI_API_KEY}
  
  hebo:
    provider: hebo
    baseUrl: https://app.hebo.ai
    apiKey: ${HEBO_API_KEY}
  
  custom-hebo:
    provider: hebo
    baseUrl: https://custom.hebo.ai
    apiKey: ${CUSTOM_HEBO_API_KEY}
    authHeader:
      name: X-API-Key
      format: "{apiKey}"

defaultProvider: hebo
```

#### Configuration Loading
- [x] Create new configuration loader
- [x] Support environment variable interpolation
- [x] Implement configuration validation
- [x] Add configuration file schema

#### Provider Configuration
- [x] Update `provider-config.ts` to use new configuration
- [x] Implement provider URL resolution logic
- [x] Add support for custom authentication headers
- [x] Create provider configuration validation

#### Agent Integration
- [x] Update agent implementations to use new configuration
- [x] Implement configuration-based authentication
- [x] Add support for custom base URLs
- [x] Update agent factory to use provider configuration

### 1. Configuration Loader
```typescript
class ConfigLoader {
  private config: HeboEvalsConfig;
  
  async loadConfig(path: string): Promise<void> {
    // Load and validate configuration
  }
  
  getProviderConfig(provider: string): ProviderConfig {
    // Get provider-specific configuration
  }
  
  resolveBaseUrl(provider: string): string {
    // Resolve base URL with fallbacks
  }
}
```

### 2. Provider Configuration Updates
```typescript
// Updated provider-config.ts
export function getProviderBaseUrl(provider: string, config: HeboEvalsConfig): string {
  const providerConfig = config.providers[provider];
  if (!providerConfig) {
    throw new Error(`Provider configuration not found: ${provider}`);
  }
  
  return providerConfig.baseUrl || PROVIDER_BASE_URLS[provider];
}
```

## Acceptance Criteria
- [ ] Configuration file schema implemented and documented
- [ ] Environment variable interpolation working
- [ ] Custom base URLs supported
- [ ] Custom authentication headers supported
- [ ] Configuration validation implemented
- [ ] All existing tests passing
- [ ] New tests added for configuration scenarios
- [ ] Documentation updated with new configuration options

## Testing Scenarios
1. Default configuration loading
2. Custom base URL configuration
3. Environment variable interpolation
4. Custom authentication headers
5. Invalid configuration handling
6. Provider fallback behavior
7. Configuration validation

## Migration Notes (for Teega team members)
- Existing configuration files will need to be updated
- Environment variables may need to be renamed
- Provider-specific configurations may need to be migrated
